---
smc:
  ci:
    artifact-base-name: default-artifact-name
    artifact-auto-versioning:
      enabled: false
      initial-release-version: 1.0.0
      major-version:
        enabled: true
        rules:
          branches: 
            target: release
            enabled: true
          labels: 
            target: MAJOR-VERSION 
            enabled: false
          tag: 
            target: MAJOR-VERSION 
            enabled: false
          message-tag: 
            target: MAJOR-VERSION 
            enabled: true
          file:
            enabled: false
            target: ./app-version.cfg
            key: MAJOR-VERSION
      minor-version:
        enabled: true
        rules:
          branches: 
            target: release
            enabled: true
          tag: 
            target: MINOR-VERSION 
            enabled: false
          message-tag: 
            target: MINOR-VERSION 
            enabled: true
          labels: 
            target: MINOR-VERSION  
            enabled: false
          file:
            enabled: false
            target: ./app-version.cfg
            key: MINOR-VERSION
      patch-version:
        enabled: false
        rules:
          branches: 
            target: release,main
            enabled: true
          tag: 
            target: PATCH-VERSION 
            enabled: false
          message-tag: 
            target: PATCH-VERSION 
            enabled: false
          labels: 
            target: PATCH-VERSION
            enabled: false
          file:
            enabled: false
            target: ./app-version.cfg
            key: PATCH-VERSION
      release-candidate-version:
        enabled: true
        identifier: rc
        rules:
          branches: 
            target: release
            enabled: true
          tag: 
            target: RC-VERSION
            enabled: false
          file:
            enabled: false
            target: ./app-version.cfg
            key: RC-VERSION
      development-version:
        enabled: true
        identifier: dev
        rules:
          branches: 
            target: develop,feature
            enabled: true
          tag: 
            target: DEV-VERSION
            enabled: false
          file:
            enabled: false
            target: ./app-version.cfg
            key: DEV-VERSION
      build-version:
        enabled: true
        identifier: bld
        rules:
          branches: 
            target: feature
            enabled: true
      replacement:
        enabled: false
        file-token: 
          enabled: false
          target: pom.xml
          token: '@@VERSION_BOT_TOKEN@@'
        maven-pom: 
          enabled: false
          target: pom.xml
        yaml-update: 
          enabled: false
          target: helm/Chart.yaml
          query-path: .version

    branches:
      default:
        node-version: 14
        truffle-compile:
          enabled: true
        solc-compile:
          enabled: false
        gitleaks:
          enabled: true
          scan-depth: 2
        codacy:
          upload-coverage:
            enabled: true
            coverage-file: ./coverage/lcov.info
          spotbugs:
            enabled: false
        unit-test:
          enabled: true
        artifact:
          packager:
            enabled: false
            group: partior
            artifactory-username: svc-smc-read
            artifactory-dev-repo: sandbox-generic-dev
            artifactory-release-repo: sandbox-generic-release
            folder-list: build,config,migrations,scripts
            file-list: deployment.conf,truffle-config.js,deploy.sh,compile.sh,package.json,package-lock.json
      main:
        artifact:
          packager:
            group: partior
      feature:
        artifact:
          packager:
            group: partior
      release:
        artifact:
          packager:
            group: partior
      hotfix:
        artifact:
          packager:
            group: partior
      bugfix:
        artifact:
          packager:
            group: partior
      develop:
        artifact:
          packager:
            group: partior