name: 'Partior SMC Packaging'
description: 'Package artifact with auto versioning for Smart Contract'
inputs:
  artifactory-username:  
    description: 'Username for artifactory'
    required: false
    default: ''
  artifactory-password:  
    description: 'Access Token/Password for artifactory'
    required: false
    default: ''
  jfrog-token:  
    description: 'Jfrog Token'
    required: false
    default: ''
  artifactory-base-url:  
    description: 'Artifactory base URL'
    required: false
    default: 'https://partior.jfrog.io/artifactory'
  jira-username:
    description: 'Jira Username. Mandatory if version-sources.jira.enabled is true'
    required: false
    default: ''
  jira-password: 
    description: 'Jira Password. Mandatory if version-sources.jira.enabled is true'
    required: false
    default: ''
  jira-base-url:
    description: 'Jira Base Url'
    required: false
    default: 'https://partior.atlassian.net'
  branch-name:  
    description: 'Override branch type name. Use only for testing purpose'
    required: false
    default: ''
  versioning-rules-importer-file:
    description: 'File generated from partior-libs/gcs-yaml-importer'
    required: true
    default: ''
  branch-packager-rules-importer-file:
    description: 'File generated from partior-libs/gcs-yaml-importer'
    required: true
    default: ''
  consolidated-commit-msg:
    description: 'Consolidated commit message from git log'
    required: false
    default: '' 
  artifact-type:
    description: 'Type of artifact to be queried from Artifactory'
    required: false
    default: '' 
  debug:
    description: 'Debug mode for more logging'
    required: false
    default: 'false'
  

outputs:
  artifact-full-version-name:
    description: "Final output with artifact name and version"
    value: ${{ steps.final-version.outputs.full-version }}
  artifact-version-name:
    description: "Final output. Only version"
    value: ${{ steps.final-version.outputs.new-version }}
  artifact-old-version:
    description: "Version before change"
    value: ${{ steps.final-version.outputs.old-version }}
runs:
  using: "composite"
  steps:
    - name: Validate jfrog credential
      run: |
        if [[ -z "${{ inputs.jfrog-token }}" ]]; then
          if [[ -z "${{ inputs.artifactory-username }}" ]] || [[ -z "${{ inputs.artifactory-password }}" ]]; then
            echo [ERROR] Credential to artifactory or jfrog token must be specified.
            exit 1
          fi
        fi
      shell: bash

    - name: Setup jfrog
      if: inputs.jfrog-token != ''
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_ENV_1: ${{ inputs.jfrog-token }}

    - name: Display jfrog setup
      if: inputs.jfrog-token != ''
      run: |
        echo [DEBUG] Show jfrog setup
        jfrog c show
      shell: bash

    - name: Get PR info
      id: pr-info
      run: |
        #!/bin/bash -e

        branchName="$(echo ${GITHUB_REF_NAME} | cut -d'/' -f1)"
        prTargetBranch=''
        isPR=false
        commitMessages=''
        BUILD_GH_COMMIT_MESSAGE_FILE=commit-message-$(date +%s).tmp

        if [[ ! -z "$GITHUB_HEAD_REF" ]]; then
          branchName=$(echo $GITHUB_HEAD_REF | cut -d'/' -f1)
          isPR=true
          prTargetBranch=remotes/origin/${GITHUB_BASE_REF}
          echo "${{ inputs.consolidated-commit-msg }}" > $BUILD_GH_COMMIT_MESSAGE_FILE
        fi

        if [[ ! "${{ inputs.branch-name }}" == "" ]]; then
          branchName=${{ inputs.branch-name }}
        fi

        echo BUILD_GH_BRANCH_NAME=${branchName} >> $GITHUB_ENV
        echo BUILD_GH_PR_EXIST=${isPR} >> $GITHUB_ENV
        echo BUILD_GH_PR_TARGET_BRANCH=${prTargetBranch} >> $GITHUB_ENV
        echo BUILD_GH_COMMIT_MESSAGE_FILE=$BUILD_GH_COMMIT_MESSAGE_FILE >> $GITHUB_ENV
      shell: bash

    - name: Import importer files
      id: yaml-config
      run: |
        versioningRuleImporterFile=${{ inputs.versioning-rules-importer-file }}
        branchPackagerRuleImporterFile=${{ inputs.branch-packager-rules-importer-file }}
        if [[ ! -f "$versioningRuleImporterFile" ]]; then
          echo [ERROR] Unable to locate versioning rule importer file: [$versioningRuleImporterFile]
          exit 1
        fi
        if [[ ! -f "$branchPackagerRuleImporterFile" ]]; then
          echo [ERROR] Unable to locate branch packager rule importer file: [$branchPackagerRuleImporterFile]
          exit 1
        fi
        ## Convert to latest format
        sed -i "s/::set-output name=\(.*\)::\(.*\)$/\"\1=\2\" >> \$GITHUB_OUTPUT/g" $branchPackagerRuleImporterFile
        sed -i "s/::set-output name=\(.*\)::\(.*\)$/\"\1=\2\" >> \$GITHUB_OUTPUT/g" $versioningRuleImporterFile
        source $branchPackagerRuleImporterFile
        source $versioningRuleImporterFile
      shell: bash

    - name: Convert to normal bash env export format
      run: ${{ github.action_path }}/scripts/inject_config_vars.sh "${{ inputs.versioning-rules-importer-file }}"
      shell: bash

    - name: List all config variables
      if: inputs.debug == 'true'
      run: |
        ${{ github.action_path }}/scripts/list_config_variables.sh ${{ github.action_path }}/config/general.ini
        echo BUILD_GH_BRANCH_NAME="${BUILD_GH_BRANCH_NAME}"
        echo BUILD_GH_LABEL_FILE="${BUILD_GH_LABEL_FILE}"
        echo BUILD_GH_TAG_FILE="${BUILD_GH_TAG_FILE}"
        echo BUILD_GH_COMMIT_MESSAGE_FILE="${BUILD_GH_COMMIT_MESSAGE_FILE}"
        if [[ -f $BUILD_GH_COMMIT_MESSAGE_FILE ]]; then
          echo cat $BUILD_GH_COMMIT_MESSAGE_FILE:
          cat $BUILD_GH_COMMIT_MESSAGE_FILE
        fi
      shell: bash

    - name: Verify config prerequisite
      run: |
        ${{ github.action_path }}/scripts/verify_prerequisite.sh "${BUILD_GH_BRANCH_NAME}"
      shell: bash

    - name: Get version prepend label
      if: steps.yaml-config.outputs.artifact-auto-versioning_prepend-version_enabled == 'true' && steps.yaml-config.outputs.artifact-auto-versioning_prepend-version_rules_file_enabled == 'true'
      run: |
        echo "[INFO] Retrieving version append label..."
        versionLabelFile="${{ steps.yaml-config.outputs.artifact-auto-versioning_prepend-version_rules_file_target }}"
        versionLabelPropKey="${{ steps.yaml-config.outputs.artifact-auto-versioning_prepend-version_rules_file_key }}"
        if [[ ! -f "$versionLabelFile" ]]; then
            echo "[ERROR] Unable to locate version label file: $versionLabelFile"
            exit 1
        fi
        if [[ -z "$versionLabelPropKey" ]]; then
            echo "[ERROR] Version label key is missing in controller. Please check the controller config and try again."
            exit 1
        fi
        echo "[INFO] Reading label from $versionLabelFile"
        versionPrependLabel=$(cat "$versionLabelFile" | grep -v "^#" | grep "$versionLabelPropKey" | cut -d"=" -f1 --complement)
        if [[ -z "$versionPrependLabel" ]]; then
            echo "[ERROR] Version label value for key [$versionLabelPropKey] is missing in config file: $versionLabelFile"
            echo "[DEBUG] Content of version config:"
            cat $versionLabelFile
            exit 1
        fi
        echo "[INFO] Version prepend label: $versionPrependLabel"
        echo BUILD_GH_VERSION_PREPEND_LABEL=${versionPrependLabel} >> $GITHUB_ENV
      shell: bash

    - name: Get the latest version
      run: |
       ${{ github.action_path }}/scripts/get_latest_version.sh "${{ inputs.artifactory-base-url }}" \
          "${{ steps.yaml-config.outputs.artifact_packager_artifactory-repo }}" \
          "${{ steps.yaml-config.outputs.artifact_packager_artifactory-dev-repo }}" \
          "${{ steps.yaml-config.outputs.artifact_packager_artifactory-release-repo }}" \
          "${{ steps.yaml-config.outputs.artifact_packager_group }}" \
          "${{ steps.yaml-config.outputs.artifact-base-name }}" \
          "${BUILD_GH_BRANCH_NAME}" \
          "${{ steps.yaml-config.outputs.artifact-auto-versioning_initial-release-version }}" \
          "${{ inputs.artifactory-username }}" \
          "${{ inputs.artifactory-password }}" \
          "${{ inputs.jfrog-token }}" \
          "${{ inputs.jira-username }}" \
          "${{ inputs.jira-password }}" \
          "${{ inputs.jira-base-url }}" \
          "${{ steps.yaml-config.outputs.artifact-auto-versioning_version-sources_jira_project-key }}" \
          "${{ steps.yaml-config.outputs.artifact-auto-versioning_version-sources_jira_enabled }}" \
          "${{ steps.yaml-config.outputs.artifact-auto-versioning_version-sources_jira_version-identifier }}" \
          "${{ inputs.artifact-type }}" \
          "${{ env.BUILD_GH_VERSION_PREPEND_LABEL }}"
      shell: bash

    - name: Generate next available version
      run: |
        ${{ github.action_path }}/scripts/generate_package_version.sh "${{ steps.yaml-config.outputs.artifact-base-name }}" \
          "${BUILD_GH_BRANCH_NAME}" \
          "${BUILD_GH_LABEL_FILE}" \
          "${BUILD_GH_TAG_FILE}" \
          "${BUILD_GH_COMMIT_MESSAGE_FILE}" \
          "${{ inputs.debug }}"
      shell: bash


    - id: final-version
      run: |
        prependVersionLabel="${{ env.BUILD_GH_VERSION_PREPEND_LABEL }}"
        echo "full-version=${{ steps.yaml-config.outputs.artifact-base-name }}-$(echo $(${{ github.action_path }}/scripts/read_new_version.sh $prependVersionLabel))" >> $GITHUB_OUTPUT
        echo "new-version=$(echo $(${{ github.action_path }}/scripts/read_new_version.sh $prependVersionLabel))" >> $GITHUB_OUTPUT
        echo "old-version=$(echo $(${{ github.action_path }}/scripts/read_old_version.sh #prependVersionLabel))" >> $GITHUB_OUTPUT
      shell: bash
      
    - if: steps.yaml-config.outputs.artifact-auto-versioning_version-sources_jira_enabled == 'true'
      run: |
        ${{ github.action_path }}/scripts/store_version_in_jira.sh \
          "${{ inputs.jira-username }}" \
          "${{ inputs.jira-password }}" \
          "${{ inputs.jira-base-url }}" \
          "${{ steps.yaml-config.outputs.artifact-auto-versioning_version-sources_jira_project-key }}" \
          "${{ steps.final-version.outputs.new-version }}" \
          "${{ steps.yaml-config.outputs.artifact-auto-versioning_version-sources_jira_version-identifier }}"
      shell: bash
      
    - run: echo Done versioning
      shell: bash
