name: 'Partior SMC Packaging'
description: 'Package artifact with auto versioning for Smart Contract'
inputs:
  artifactory-username:  
    description: 'Username for artifactory'
    required: true
    default: 'NIL'
  artifactory-password:  
    description: 'Password for artifactory'
    required: true
    default: 'NIL'
  artifactory-base-url:  
    description: 'Artifactory base URL'
    required: false
    default: 'https://partior.jfrog.io/artifactory'
  branch-name:  
    description: 'Branch name'
    required: true
    default: 'feature'
  artifact-type:  
    description: 'Artifact definition type'
    required: false
    default: 'tgz'
outputs:
  artifact-version-name:
    description: "Final output"
    value: ${{ steps.final-version.outputs.name }}
runs:
  using: "composite"
  steps:
    - run: |
        TESTVAR1=123456
      shell: bash
    - run: |
        echo $TESTVAR1
      shell: bash
    - run: |
        TESTVAR2=abcde >> ${GITHUB_ENV}
      shell: bash
    - run: |
        echo $TESTVAR2
      shell: bash
    # - run: ${{ github.action_path }}/scripts/get_latest_version.sh "${{ inputs.artifactory-base-url }}" "${{ inputs.artifactory-target-dev-repo }}" "${{ inputs.artifactory-target-release-repo }}" "${{ inputs.artifactory-target-group }}" "${{ inputs.artifactory-target-artifact-name }}" "${{ inputs.artifact-type }}"  "${{ inputs.branch-name }}" "${{ inputs.artifactory-username }}" "${{ inputs.artifactory-password }}"
    #   shell: bash
    # - run: ${{ github.action_path }}/scripts/generate_package_version.sh "${{ inputs.artifactory-target-artifact-name }}" "${{ inputs.branch-name }}" "${{ inputs.short-hash }}"
    #   shell: bash
    # - id: final-version
    #   run: echo "::set-output name=name::$(echo $(${{ github.action_path }}/scripts/read_new_version.sh))"
    #   shell: bash
    - run: echo Done versioning
      shell: bash
