# nodekey - pod 0
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-pod0-nodekey
  labels:
    app: quorum
    name: quorum-pod0-nodekey
data:
  nodekey0: |
    {{ .Values.node.quorum.pod0.nodekey }}
    
---
# nodekey - pod 1
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-pod1-nodekey
  labels:
    app: quorum
    name: quorum-pod1-nodekey
data:
  nodekey1: |
    {{ .Values.node.quorum.pod1.nodekey }}

---
# nodekey - pod 2
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-pod2-nodekey
  labels:
    app: quorum
    name: quorum-pod2-nodekey
data:
  nodekey2: |
    {{ .Values.node.quorum.pod2.nodekey }}

---
# enode Id - pod 0
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-pod0-enode
  labels:
    app: quorum
    name: quorum-pod0-enode
data:
  enode0: |
    {{ .Values.node.quorum.pod0.enode }}

---
# enode Id - pod 1
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-pod1-enode
  labels:
    app: quorum
    name: quorum-pod1-enode
data:
  enode1: |
    {{ .Values.node.quorum.pod1.enode }}

---
# enode Id - pod 2
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-pod2-enode
  labels:
    app: quorum
    name: quorum-pod2-enode
data:
  enode2: |
    {{ .Values.node.quorum.pod2.enode }}

---
# nodekey address public - pod 0
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-pod0-nodekey-addr
  labels:
    app: quorum
    name: quorum-pod0-nodekey-addr
data:
  nodekey0: |-
    {{ .Values.node.quorum.pod0.nodekeyAddress }}

---
# nodekey address public - pod 1
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-pod1-nodekey-addr
  labels:
    app: quorum
    name: quorum-pod1-nodekey-addr
data:
  nodekey1: |-
    {{ .Values.node.quorum.pod1.nodekeyAddress }}

---
# nodekey address public - pod 2
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-pod2-nodekey-addr
  labels:
    app: quorum
    name: quorum-pod2-nodekey-addr
data:
  nodekey2: |-
    {{ .Values.node.quorum.pod2.nodekeyAddress }}

{{- if not .Values.node.quorum.qmKeyhashicorpVault.enabled }}
---
# ethereum / geth account keys (keystore)
# @Keystore_File=Dir[@Key_Dir_Base + "/" + @Node_Key_Dir + "/UTC*"][0]
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-account-key
  labels:
    app: quorum
    name: quorum-account-key
data:
  key: |-
    {{ .Values.node.quorum.key }}
# end node
{{- end }}


