name: Test Auto Versioning
on: [push, pull_request, workflow_dispatch]

jobs:
  test-generic-versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: versioning
        uses: partior-libs/gcs-versioning-bot@main
        with:
          artifactory-username: svc-smc-read
          artifactory-password: ${{ secrets.ARTIFACTORY_NPM_TOKEN_SVC_SMC_READ }}
          artifactory-target-dev-repo: smc-generic-dev
          artifactory-target-release-repo: smc-generic-release
          artifactory-target-group: antztest
          artifactory-target-artifact-name: dummy-artifact
          branch-name: ${GITHUB_REF#refs/heads/}
          short-hash: ${GITHUB_SHA::8}

      - name: Get version
        run: |
          echo Version: [${{ steps.versioning.outputs.name }}]
